# Site settings
title: "Rudra's Yard"
email: rudra.nil.basu.1996@gmail.com
description: "Random stuff."
baseurl: ""
url: "http://rudranilbasu.github.io/"
title_description: "Just another random guy trying to make AL 288-1 proud"
title_image: "https://scontent.fccu3-1.fna.fbcdn.net/v/t1.0-9/17309412_1374739672596050_1699355082050939316_n.jpg?oh=8ef59b9c6c26a2b7ca76a78751598a74&oe=5927DEC7"
google_analytics: ""
disqus_account: r_n_b
github_repository: https://github.com/RudraNilBasu
addthis_id: 
post_limit: 5

# Social usernames/URLs
twitter_username: RudraNilBasu
github_username:  RudraNilBasu
instagram_username: RudraNilBasu
linkedin_link: https://in.linkedin.com/in/rudra-nil-basu-7a1679a4
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link: facebook.com/rudra.n.basu

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/RudraNilBasu\">RudraNilBasu</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/RudraNilBasu\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

#
gems:
  - jekyll-gist # plugin to add github gist (https://github.com/jekyll/jekyll-gist)

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
